version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 7vXp3Zs!9Qw4
      MYSQL_DATABASE: movierama
      MYSQL_USER: movierama_user
      MYSQL_PASSWORD: 9k8jH6#z3LwP
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=movierama_user
      - DATABASE_PASSWORD=9k8jH6#z3LwP
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data: